### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by hxlnt** [dustmop/makechr#15]
The latest release on PyPi is version 1.4 (October 2017). It would be awesome to get an update there! Thanks!

https://pypi.org/project/Makechr/

**Comment by dustmop** [comment]
Thanks for filing the issue! I promise to get a new release up by the end of April. There's only been a few commits since the 1.4 release (no time for development in 2018), so I want to finish some of these open issues first.

**Comment by dustmop** [comment]
My self-imposed deadline is going to have to slip a few days, but I'm confident that I'll be able to release a new version this upcoming weekend.

**Comment by dustmop** [comment]
Version 1.5 has been released: https://github.com/dustmop/makechr/releases/tag/1.5
