### ISSUE TITLE
Missing Font File

### ISSUE THREAD

**Issue by jcordial** [dustmop/makechr#2]
Whenever the package is installed with `pip`, it doesn't seem to include the res folder containing the font graphics necessary to create the nametable graphic. It would also seem the rom creation also depends on the aforementioned font file, so neither feature works as intended.

This is what scientists call "a real bummer", because for the most part this is a fantastic resource.

**Comment by dustmop** [comment]
@jcordial I'm very sorry for my late reply, I didn't have notifications enabled for some reason!

Version 1.1 is now available and fixes this issue, you can upgrade now:

`pip install makechr --upgrade`

That's strange that you say it breaks rom creation, that shouldn't be the case. Could you provide the command you're using to try and build a rom?
